sudo: false
language: java
jdk:
- oraclejdk8
script:
- mvn clean verify
- ant test
env:
  global:
    secure: "N28Gewdx09KG+NAT/7VotHhI/xTaNdXWBpLTi3hoQfAbegdo9srt2pvw9oY6rT3vGyM1MsUwA78Uqb2+ls9yMm0MsI+uQH0A4NtkOoD2/8alLOsNhAjcK+w0NjURWSwcOrH4h6ibbZKWO+J6paJFNX/EU/m3QxH83uYonir2RBs="

addons:
  coverity_scan:
    project:
      name: martinpaljak/ant-javacard
    notification_email: martin@martinpaljak.net
    build_command: ant jcpro
    branch_pattern: coverity

deploy:
  api-key:
    secure: Z2jzWVPpB3Yq4+voY1cMDaq/j+qpYIyLCQTKSuWwbETxzrgoMo88X1oRA4ab82HRSpL5M3C5DFTK+SMKyEcNm5owGdYLOYSkIwR9p9KnsB7/eMJtg9O8PyPAFZbFG40GBA1XXVPTQxFYxlQBsRK5kgVCdVUtkmloDajPaUIvNng=
  provider: releases
  prerelease: true
  file: target/ant-javacard.jar
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - $HOME/.m2
