on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - next
  pull_request:
    branches:
      - master

concurrency:
  group: robot
  cancel-in-progress: false

permissions:
  contents: write

name: Build robot

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 8, 11, 17, 21, 25 ]
    name: Java ${{ matrix.java }}
    env:
      PUBLISH: ${{ matrix.java == '17' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' || startsWith(github.ref, 'refs/tags/v') ) }}
      RELEASE: ${{ matrix.java == '17' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0 # To make git describe give the intended output
          fetch-tags: true
      - name: Setup java
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Set up publishing
        if: env.PUBLISH == 'true'
        uses: martinpaljak/maven-ssh-deploy@v2
        with:
          host: mvn.javacard.pro
          key: ${{ secrets.SSH_KEY }}
          fingerprint: SHA256:auiF3nHWvDmvq2stDl+QEECCqMcDp+FY1/bDRnvxpRw
      - name: Build and deploy
        if: matrix.java != 8
        run: ./mvnw -B -U deploy -Dmaven.deploy.skip=${{ env.PUBLISH != 'true' }}
      - name: Run ANT tests
        run: ant test dist
      - name: Get SHA-256 of ant-javacard.jar
        run: echo "JARSUM=$(shasum -a 256 --tag ant-javacard.jar)" >> "$GITHUB_ENV"
      - name: Upload
        if: env.PUBLISH == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: ant-javacard.jar
          path: ant-javacard.jar
      - name: Release
        if: env.RELEASE == 'true'
        uses: softprops/action-gh-release@v3.0.3
        with:
          files: |
            ant-javacard.jar
          fail_on_unmatched_files: true
          body: "Release ${{ github.ref_name }}, `${{ env.JARSUM }}` (built with JDK-17)"
          prerelease: true # manually promoted
