on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
name: Robot builder
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17, 21 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - name: Setup java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Set SSH key
        if: github.event_name != 'pull_request'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add host key
        if: github.event_name != 'pull_request'
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Run Maven for capfile
        if: matrix.java != 8
        run: ./mvnw -T1C -B -U verify
      - name: Run ANT tests
        if: matrix.java != 21
        run: ant test dist
      - name: Deploy package or snapshot
        if: github.event_name != 'pull_request' && matrix.java == '11'
        run: ./mvnw -B -U deploy
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.java == '11'
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ant-javacard.jar
          fail_on_unmatched_files: true
          body: Release ${{ github.ref_name }}
          prerelease: true # manually promoted
